// ISO 3166-1 alpha-2 country codes with names, flag emojis, and phone prefixes
export interface Country {
  code: string;
  name: string;
  flag: string;
  phonePrefix: string;
}

// Priority countries to show at the top of the list
export const priorityCountryCodes = ["US", "GB", "ES", "PT", "FR", "IT"];

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", phonePrefix: "+93" },
  { code: "AL", name: "Albania", flag: "🇦🇱", phonePrefix: "+355" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", phonePrefix: "+213" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", phonePrefix: "+376" },
  { code: "AO", name: "Angola", flag: "🇦🇴", phonePrefix: "+244" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", phonePrefix: "+1268" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", phonePrefix: "+54" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", phonePrefix: "+374" },
  { code: "AU", name: "Australia", flag: "🇦🇺", phonePrefix: "+61" },
  { code: "AT", name: "Austria", flag: "🇦🇹", phonePrefix: "+43" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", phonePrefix: "+994" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", phonePrefix: "+1242" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", phonePrefix: "+973" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", phonePrefix: "+880" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", phonePrefix: "+1246" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", phonePrefix: "+375" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", phonePrefix: "+32" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", phonePrefix: "+501" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", phonePrefix: "+229" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", phonePrefix: "+975" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", phonePrefix: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", phonePrefix: "+387" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", phonePrefix: "+267" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", phonePrefix: "+55" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", phonePrefix: "+673" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", phonePrefix: "+359" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", phonePrefix: "+226" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", phonePrefix: "+257" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", phonePrefix: "+238" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", phonePrefix: "+855" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", phonePrefix: "+237" },
  { code: "CA", name: "Canada", flag: "🇨🇦", phonePrefix: "+1" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", phonePrefix: "+236" },
  { code: "TD", name: "Chad", flag: "🇹🇩", phonePrefix: "+235" },
  { code: "CL", name: "Chile", flag: "🇨🇱", phonePrefix: "+56" },
  { code: "CN", name: "China", flag: "🇨🇳", phonePrefix: "+86" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", phonePrefix: "+57" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", phonePrefix: "+269" },
  { code: "CG", name: "Congo", flag: "🇨🇬", phonePrefix: "+242" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", phonePrefix: "+506" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", phonePrefix: "+385" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", phonePrefix: "+53" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", phonePrefix: "+357" },
  { code: "CZ", name: "Czechia", flag: "🇨🇿", phonePrefix: "+420" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", phonePrefix: "+45" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", phonePrefix: "+253" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", phonePrefix: "+1767" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", phonePrefix: "+1809" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", phonePrefix: "+593" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", phonePrefix: "+20" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", phonePrefix: "+503" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", phonePrefix: "+240" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", phonePrefix: "+291" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", phonePrefix: "+372" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", phonePrefix: "+268" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", phonePrefix: "+251" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", phonePrefix: "+679" },
  { code: "FI", name: "Finland", flag: "🇫🇮", phonePrefix: "+358" },
  { code: "FR", name: "France", flag: "🇫🇷", phonePrefix: "+33" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", phonePrefix: "+241" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", phonePrefix: "+220" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", phonePrefix: "+995" },
  { code: "DE", name: "Germany", flag: "🇩🇪", phonePrefix: "+49" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", phonePrefix: "+233" },
  { code: "GR", name: "Greece", flag: "🇬🇷", phonePrefix: "+30" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", phonePrefix: "+1473" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", phonePrefix: "+502" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", phonePrefix: "+224" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", phonePrefix: "+245" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", phonePrefix: "+592" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", phonePrefix: "+509" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", phonePrefix: "+504" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", phonePrefix: "+36" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", phonePrefix: "+354" },
  { code: "IN", name: "India", flag: "🇮🇳", phonePrefix: "+91" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", phonePrefix: "+62" },
  { code: "IR", name: "Iran", flag: "🇮🇷", phonePrefix: "+98" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", phonePrefix: "+964" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", phonePrefix: "+353" },
  { code: "IL", name: "Israel", flag: "🇮🇱", phonePrefix: "+972" },
  { code: "IT", name: "Italy", flag: "🇮🇹", phonePrefix: "+39" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", phonePrefix: "+1876" },
  { code: "JP", name: "Japan", flag: "🇯🇵", phonePrefix: "+81" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", phonePrefix: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", phonePrefix: "+7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", phonePrefix: "+254" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", phonePrefix: "+686" },
  { code: "KP", name: "North Korea", flag: "🇰🇵", phonePrefix: "+850" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", phonePrefix: "+82" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", phonePrefix: "+965" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", phonePrefix: "+996" },
  { code: "LA", name: "Laos", flag: "🇱🇦", phonePrefix: "+856" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", phonePrefix: "+371" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", phonePrefix: "+961" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", phonePrefix: "+266" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", phonePrefix: "+231" },
  { code: "LY", name: "Libya", flag: "🇱🇾", phonePrefix: "+218" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", phonePrefix: "+423" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", phonePrefix: "+370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", phonePrefix: "+352" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", phonePrefix: "+261" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", phonePrefix: "+265" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", phonePrefix: "+60" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", phonePrefix: "+960" },
  { code: "ML", name: "Mali", flag: "🇲🇱", phonePrefix: "+223" },
  { code: "MT", name: "Malta", flag: "🇲🇹", phonePrefix: "+356" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", phonePrefix: "+692" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", phonePrefix: "+222" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", phonePrefix: "+230" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", phonePrefix: "+52" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", phonePrefix: "+691" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", phonePrefix: "+373" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", phonePrefix: "+377" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", phonePrefix: "+976" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", phonePrefix: "+382" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", phonePrefix: "+212" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", phonePrefix: "+258" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", phonePrefix: "+95" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", phonePrefix: "+264" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", phonePrefix: "+674" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", phonePrefix: "+977" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", phonePrefix: "+31" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", phonePrefix: "+64" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", phonePrefix: "+505" },
  { code: "NE", name: "Niger", flag: "🇳🇪", phonePrefix: "+227" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", phonePrefix: "+234" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", phonePrefix: "+389" },
  { code: "NO", name: "Norway", flag: "🇳🇴", phonePrefix: "+47" },
  { code: "OM", name: "Oman", flag: "🇴🇲", phonePrefix: "+968" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", phonePrefix: "+92" },
  { code: "PW", name: "Palau", flag: "🇵🇼", phonePrefix: "+680" },
  { code: "PS", name: "Palestine", flag: "🇵🇸", phonePrefix: "+970" },
  { code: "PA", name: "Panama", flag: "🇵🇦", phonePrefix: "+507" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", phonePrefix: "+675" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", phonePrefix: "+595" },
  { code: "PE", name: "Peru", flag: "🇵🇪", phonePrefix: "+51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", phonePrefix: "+63" },
  { code: "PL", name: "Poland", flag: "🇵🇱", phonePrefix: "+48" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", phonePrefix: "+351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", phonePrefix: "+974" },
  { code: "RO", name: "Romania", flag: "🇷🇴", phonePrefix: "+40" },
  { code: "RU", name: "Russia", flag: "🇷🇺", phonePrefix: "+7" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", phonePrefix: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", phonePrefix: "+1869" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", phonePrefix: "+1758" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", phonePrefix: "+1784" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", phonePrefix: "+685" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", phonePrefix: "+378" },
  { code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹", phonePrefix: "+239" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", phonePrefix: "+966" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", phonePrefix: "+221" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", phonePrefix: "+381" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", phonePrefix: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", phonePrefix: "+232" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", phonePrefix: "+65" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", phonePrefix: "+421" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", phonePrefix: "+386" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", phonePrefix: "+677" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", phonePrefix: "+252" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", phonePrefix: "+27" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", phonePrefix: "+211" },
  { code: "ES", name: "Spain", flag: "🇪🇸", phonePrefix: "+34" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", phonePrefix: "+94" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", phonePrefix: "+249" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", phonePrefix: "+597" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", phonePrefix: "+46" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", phonePrefix: "+41" },
  { code: "SY", name: "Syria", flag: "🇸🇾", phonePrefix: "+963" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", phonePrefix: "+886" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", phonePrefix: "+992" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", phonePrefix: "+255" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", phonePrefix: "+66" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", phonePrefix: "+670" },
  { code: "TG", name: "Togo", flag: "🇹🇬", phonePrefix: "+228" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", phonePrefix: "+676" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", phonePrefix: "+1868" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", phonePrefix: "+216" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", phonePrefix: "+90" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", phonePrefix: "+993" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", phonePrefix: "+688" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", phonePrefix: "+256" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", phonePrefix: "+380" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", phonePrefix: "+971" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", phonePrefix: "+44" },
  { code: "US", name: "United States", flag: "🇺🇸", phonePrefix: "+1" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", phonePrefix: "+598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", phonePrefix: "+998" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", phonePrefix: "+678" },
  { code: "VA", name: "Vatican City", flag: "🇻🇦", phonePrefix: "+379" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", phonePrefix: "+58" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", phonePrefix: "+84" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", phonePrefix: "+967" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", phonePrefix: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", phonePrefix: "+263" },
];

export function getCountryByCode(code: string): Country | undefined {
  return countries.find(c => c.code === code);
}

export function getCountryByName(name: string): Country | undefined {
  return countries.find(c => c.name.toLowerCase() === name.toLowerCase());
}

// Get countries sorted with priority countries first
export function getSortedCountries(): { priority: Country[]; others: Country[] } {
  const priority = priorityCountryCodes
    .map(code => countries.find(c => c.code === code))
    .filter((c): c is Country => c !== undefined);
  
  const others = countries
    .filter(c => !priorityCountryCodes.includes(c.code))
    .sort((a, b) => a.name.localeCompare(b.name));
  
  return { priority, others };
}