project_id = "mtbsuzhkxzhgmijeafnq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.handle-checkout-success]
    verify_jwt = false
  [functions.send-contact-notification]
    verify_jwt = false
